### ISSUE TITLE
Image rendering

### ISSUE THREAD

**Issue by arenzana** [wasamasa/nov.el#50] opened 2019-03-18 14:55 UTC
My emacs is not compiled for image support. When I hit a png file, it obviously doesn't render, but it doesn't load the rest of the chapter. This is the error I receive:
`Invalid image type ‘png’`

Is there a way to include an option to not render images and just put a place holder in its place instead?

**Comment by wasamasa** [comment] 2019-03-21 18:52
Ouch. This might be something beyond this package as it heavily relies on shr.el.  Could you please try whether using `M-x eww` or `M-x eww-open-file` fails in the same way on a HTML document containing images?

**Comment by wasamasa** [comment] 2019-03-21 18:53
Also, how did you compile Emacs without image support?

**Comment by arenzana** [comment] 2019-03-21 18:59
@wasamasa thanks for getting back. I did `eww-open-file` against a saved copy of this link: https://www.theverge.com/2019/3/21/18274592/houseparty-app-ceo-sima-sistani-ben-rubin-meerkat
and got the following, which looks like what I'm looking for:

![Screen Shot 2019-03-21 at 2 57 22 PM](https://user-images.githubusercontent.com/5133407/54777940-d5539a80-4be9-11e9-8b58-335b8d4c64c5.png)

Also, https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb#L40
Thanks!

**Comment by wasamasa** [comment] 2019-03-21 19:38
Alright, then it's not shr.el, but my adjustments to it that try to use Imagemagick for rescalable images.

**Comment by wasamasa** [comment] 2019-03-21 20:16
I can't reproduce this on Linux with an Emacs compiled with `--without-imagemagick` when visiting an EPUB containing images. Could you please send me the problematic file?

**Comment by ghost** [comment] 2019-08-11 16:53
I have an EPUB book with JPEG images. I get the `Invalid image type ‘jpeg’` error message. I use Gentoo. Emacs is built with the `-X` USE flag, which means `--without-x`. It doesn't matter if I enable/disable the `imagemagick` and/or `jpeg` USE flags: I always get this error message. This is expected because inside the emacs ebuild the `imagemagick` and `jpeg` USE flags have no effect at all if `X` is disabled. This means that `-X -imagemagick -jpeg` simply translates to `--without-x` only instead of `--without-x --without-imagemagick --without-jpeg`. I should probably report this to Gentoo developers...

Anyway I think having a nov.el option for disabling images would be great because it would work without rebuilding emacs.

**Comment by wasamasa** [comment] 2019-08-11 16:58
Please do not hijack existing threads. Given the lack of reproducer after all that time, I'm closing this one. If you can provide one, feel free to open a new thread. And yes, report Gentoo problems to Gentoo developers, I'm not one of them.

**Closed as completed by wasamasa** 2019-08-11 16:58 UTC
